### PR TITLE
Set nullcollation value to low and align with hive

### PR DESCRIPTION
**Pull request by huangxiaopingRD**
As described by issue
https://github.com/linkedin/coral/issues/85

### CODE REVIEW

**Comment by uzshao** [comment]
@huangxiaopingRD Great!  Can you add a test case to `HiveToTrinoConverterTest` as well?

**Comment by huangxiaopingRD** [comment]
> @huangxiaopingRD Great! Can you add a test case to `HiveToTrinoConverterTest` as well?

@uzshao I have added it, please review it

**Comment by uzshao** [comment]
LGTM!

**Comment by huangxiaopingRD** [comment]
@wmoustafa Can you help review for this merge request? Thanks!

**Review by ljfgem — APPROVED** [review]
LGTM, thanks @huangxiaopingRD 
No regression in integration test.

**Comment by huangxiaopingRD** [comment]
> LGTM, thanks @huangxiaopingRD
> No regression in integration test.

@ljfgem Thank you for your review, because this change will really change the relevant test cases. Do I need to make some changes?

**Comment by ljfgem** [comment]
> > LGTM, thanks @huangxiaopingRD
> > No regression in integration test.
> 
> @ljfgem Thank you for your review, because this change will really change the relevant test cases. Do I need to make some changes?

What test cases do you think we need to change? As the build check passed for this PR, I think there is no change needed.

**Review by wmoustafa — APPROVED** [review]

**Comment by huangxiaopingRD** [comment]
> > > LGTM, thanks @huangxiaopingRD
> > > No regression in integration test.
> > 
> > 
> > @ljfgem Thank you for your review, because this change will really change the relevant test cases. Do I need to make some changes?
> 
> What test cases do you think we need to change? As the build check passed for this PR, I think there is no change needed.

@ljfgem Thanks.Can you help merge with this change?

**Pull request merged**
