### PR TITLE
Fail build on checkstyle errors

### PR DESCRIPTION
**Pull request by cwsteinbach**
This patch includes the following changes:

- Adds LinkedIn's Checkstyle configuration to grade/checkstyle
- Enables Checkstyle as part of the default build process in build.gradle
- Ensures that Checkstyle violations result in build failures
- Modifies the formatting in ~150 source files to eliminate checkstyle failures.

### CODE REVIEW

**Comment by wmoustafa** [comment]
Thanks for this patch. Since we are still maintaining the internal version of Coral, merging this now will make it very difficult though to sync with the internal repo. Since internal repo is being transitioned to this repo, let us wait till we have fully transitioned before merging this. cc: @shardulm94 @funcheetah

**Comment by shardulm94** [comment]
@cwsteinbach Should we consider https://github.com/diffplug/spotless? It will auto format code, developers no longer need to worry about style when writing code, reviewers no longer need to worry about style when reviewing. Spotless for Java has two formatters 1) Google (opinionated as per Google's Java style guidelines) 2) Eclipse (customizable). In one of our internal repo's we have used the Google formatter. We just accept the Google style guidelines rather than worry about tweaking to adjust to every reviewer's/team member's taste.

**Comment by cwsteinbach** [comment]
Closing this PR in favor of #33

**Comment by cwsteinbach** [comment]
Superseded by #33

**Pull request closed without merging**
