### PR TITLE
Rename coral-presto module to coral-trino

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
cc @wmoustafa

**Comment by wmoustafa** [comment]
Thanks for filing this PR! Are you planning to rename the files and the contents of the files in a separate patch?

**Comment by findepi** [comment]
Ideally would like to take care of this as a follow up.

**Review by wmoustafa — APPROVED** [review]

**Comment by findepi** [comment]
Follow up: https://github.com/linkedin/coral/pull/69

**Pull request merged**
