### PR TITLE
Use compileOnly for trino-parser shading

### PR DESCRIPTION
**Pull request by ljfgem**
Tested it by publishing to local maven and integrating with Trino.

### CODE REVIEW

**Comment by shenodaguirguis** [comment]
do we still need to shade?

**Comment by wmoustafa** [comment]
> do we still need to shade?

Since there was an issue last time we did `compileOnly` without shading, we ended up with using shading (but also for shading to work, we still need `compileOnly`).

**Comment by wmoustafa** [comment]
@ljfgem Could you please check the failing tests in the workflow? I know it should build locally.

**Comment by ljfgem** [comment]
@wmoustafa Same build issue which recovered by itself before:
```
> Task :coral-spark:spark3Test

Gradle suite > Gradle test > com.linkedin.coral.spark.TransportableUDFMapTest.testLookupExistButNotReadyForSpark3 FAILED
    java.net.BindException at Net.java:-2

Gradle suite > Gradle test > com.linkedin.coral.spark.TransportableUDFMapTest.testLookupWithSparkSession FAILED
    java.net.BindException at Net.java:-2


6 tests completed, 3 failed
Gradle suite > Gradle test > com.linkedin.coral.spark.TransportableUDFMapTest.testScalaVersionWithSparkSession FAILED
    java.net.BindException at Net.java:-2
```

**Comment by ljfgem** [comment]
@wmoustafa it just recovered by itself.

**Review by wmoustafa — APPROVED** [review]

**Pull request merged**
