### PR TITLE
Add a SqlReturnTypeInference strategy for extract_union UDF to deal w…

### PR DESCRIPTION
**Pull request by rzhang10**
…ith 1/2 arg cases

@wmoustafa @funcheetah @shenodaguirguis

### CODE REVIEW

**Comment by funcheetah** [comment]
@rzhang10 could you test the 2-arg case on cluster and run regression tests for this PR? Thanks

**Comment by rzhang10** [comment]
When I previously tested this, it seems that coral-schema needs additional change to make this work. Actually it turned out I mistakenly did not include the patch into integration testing. Today I tested again and it works in spark.

**Comment by ljfgem** [comment]
@rzhang10 could you run integration tests for this PR?

**Review by funcheetah — APPROVED** [review]

**Comment by funcheetah** [comment]
Thanks @rzhang10 . Please run integration tests and make sure there is no regression before merging.

**Comment by rzhang10** [comment]
> Thanks @rzhang10 . Please run integration tests and make sure there is no regression before merging.

tbh, I don't expect there will be any regression since this just affect extract_union 2 arg cases which were not supported before, it doesn't change any existing logic, but i think i can run intg test anyways.

**Comment by shenodaguirguis** [comment]
30 commits! :-) rebase glitch?

**Comment by rzhang10** [comment]
> 30 commits! :-) rebase glitch?

yeah indeed... just fixed it..

**Review by shenodaguirguis — APPROVED** [review]

**Review by ljfgem — APPROVED** [review]
No regression in integration test.

**Pull request merged**
