### PR TITLE
Update calcite to fix handling of queries with nested group by

### PR DESCRIPTION
**Pull request by losipiuk**
Depends on the linkedin-calcite release which includes: https://github.com/linkedin/linkedin-calcite/pull/38

Fixes: https://github.com/linkedin/coral/issues/72

cc: @wmoustafa @findepi

### CODE REVIEW

**Comment by findepi** [comment]
@losipiuk thank you!

**Comment by wmoustafa** [comment]
Thanks @losipiuk! You can address the `TODO` item since version `1.21.0.146` is now published (thanks to @rzhang10).

**Comment by losipiuk** [comment]
Thanks for heads up.
PTAL @wmoustafa

**Comment by losipiuk** [comment]
Friendly ping @wmoustafa :)

**Review by wmoustafa — APPROVED** [review]

**Pull request merged**
