### PR TITLE
[CORAL-HIVE] Improve Artifacts Resolver Log.

### PR DESCRIPTION
**Pull request by slfan1989**
### What changes are proposed in this pull request, and why are they necessary?

[CORAL-LOG] Improve Artifacts Resolver Log.

I am reading the code of coral, in Artifact Resolver we have used slf4j, we can use placeholders directly in the log.
This is a small improvement.

### CODE REVIEW

**Comment by slfan1989** [comment]
@ljfgem Can you help review this PR? Thank you very much!

**Comment by ljfgem** [comment]
> @ljfgem Can you help review this PR? Thank you very much!

@slfan1989 Thanks for the PR, please solve formatting errors by running `./gradlew spotlessApply`.

**Comment by wmoustafa** [comment]
Thanks for the improvement @slfan1989.

**Review by ljfgem — APPROVED** [review]
lgtm, thanks @slfan1989

**Comment by slfan1989** [comment]
@ljfgem @wmoustafa Thanks for reviewing the code!

**Pull request merged**
